export const incompatibleFonts = [
  "Allkin",
  "Chiron GoRound TC",
  "Chiron Hei HK",
  "Chiron Sung HK",
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Two Tone",
  "Material Icons Sharp",
  "Material Symbols Outlined",
  "Material Symbols Sharp",
  "Material Symbols",
  "Material Symbols Rounded",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA Guides",
  "Playwrite AU SA",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC Guides",
  "Playwrite AU VIC",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BR",
  "Playwrite BE WAL Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CL",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CU Guides",
  "Playwrite CU",
  "Playwrite CO Guides",
  "Playwrite CZ",
  "Playwrite DE Grund",
  "Playwrite CZ Guides",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE LA Guides",
  "Playwrite DK Loopet Guides",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite ES",
  "Playwrite ES Deco Guides",
  "Playwrite ES Deco",
  "Playwrite ES Guides",
  "Playwrite FR Trad",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad Guides",
  "Playwrite GB J Guides",
  "Playwrite GB J",
  "Playwrite GB S",
  "Playwrite HR",
  "Playwrite GB S Guides",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite HU Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite MX",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite NZ",
  "Playwrite NZ Basic",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ Guides",
  "Playwrite PE",
  "Playwrite PE Guides",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite RO Guides",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ Guides",
  "Playwrite TZ",
  "Playwrite US Modern",
  "Playwrite US Modern Guides",
  "Playwrite US Trad Guides",
  "Playwrite US Trad",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite BR Guides",
  "Playwrite DE VA",
  "Playwrite IE",
  "Playwrite IT Trad Guides",
  "Wavefont"
];